package Vista;

import Controlador.c_Formulario;
import Controlador.validar;
import Modelo.Alumno;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jony
 */
public class frm_Promedio extends javax.swing.JFrame {

    /**
     * Creates new form frm_Promedio
     */
    validar val = new validar();///se instancia un objeto de la clase que  hemos creado llamado validar para usar sus metodos 
    c_Formulario control = new c_Formulario();

    public frm_Promedio() {
        initComponents();
        this.setLocationRelativeTo(null);//para que el formulario aparesca en el centro de laq pantalla
        tblDatos.setModel(tabla());///se le colocan los nombres a las columnas de la tabla 
        ////el promedio lo agregamos por medio de un  comboBox para evitar errores con las notas de parte del usuario
        cboPromedio.setModel(notas());///agregamos los elementos al comboBox atraves de un metodo
        lblcantAlumnos.setText(String.valueOf(control.mostrar().size()));/// cantidad de alumnos
        //----
        ///atraves del objeto de la clase validar llamamos al metodo para que solo permita el ingreso de letras(L) o numeros(N) en nuestros textBox
        val.val_caracteres(txtMatricula, "N");
        val.val_caracteres(txtNombre, "L");
        val.val_caracteres(txtApellidoP, "L");
        val.val_caracteres(txtApellidoM, "L");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @return
     */
    //////
    public DefaultComboBoxModel notas() {
        ///elementos del combo
        ///utilizamos un combo para controlar que el usuario no ingrese una nota no valida
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("00");
        modelo.addElement("01");
        modelo.addElement("02");
        modelo.addElement("03");
        modelo.addElement("04");
        modelo.addElement("05");
        modelo.addElement("06");
        modelo.addElement("07");
        modelo.addElement("08");
        modelo.addElement("09");
        modelo.addElement("10");
        modelo.addElement("11");
        modelo.addElement("12");
        modelo.addElement("13");
        modelo.addElement("14");
        modelo.addElement("15");
        modelo.addElement("16");
        modelo.addElement("17");
        modelo.addElement("18");
        modelo.addElement("19");
        modelo.addElement("20");

        return modelo;
    }

    public DefaultTableModel tabla() {
        DefaultTableModel modeloT = new DefaultTableModel();///creamos un objeto modelo para asignarlo al tblDatos
        /// le colocamos los titulos a las columnas
        modeloT.addColumn("Matricula");
        modeloT.addColumn("Nombre");
        modeloT.addColumn("Apellido P");
        modeloT.addColumn("Apellido M");
        modeloT.addColumn("Promedio");

        return modeloT;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        cboPromedio = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        BtnMostar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        pRespuestas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPrimerP = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblMedia = new javax.swing.JLabel();
        lblcantAlumnos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Promedio");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Promedios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 200, 60));

        pDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pDatos.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Matricula");

        txtMatricula.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nombres");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Apellido P");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Promedio");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Apellido M");

        cboPromedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pDatosLayout = new javax.swing.GroupLayout(pDatos);
        pDatos.setLayout(pDatosLayout);
        pDatosLayout.setHorizontalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDatosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cboPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDatosLayout.createSequentialGroup()
                        .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtApellidoP)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDatosLayout.setVerticalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(pDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, 210));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 102, 153));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 140, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 102, 153));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save (2).png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 140, 40));

        BtnMostar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnMostar.setForeground(new java.awt.Color(0, 102, 153));
        BtnMostar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/150_glasses.png"))); // NOI18N
        BtnMostar.setText("Mostrar");
        BtnMostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 140, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 102, 153));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 140, -1));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 740, 210));

        pRespuestas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pRespuestas.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Primer Puesto: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Promedio: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Media del aula");

        lblPrimerP.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        lblPromedio.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        lblMedia.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        lblcantAlumnos.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Cantidad de alumnos:");

        javax.swing.GroupLayout pRespuestasLayout = new javax.swing.GroupLayout(pRespuestas);
        pRespuestas.setLayout(pRespuestasLayout);
        pRespuestasLayout.setHorizontalGroup(
            pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRespuestasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRespuestasLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pRespuestasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrimerP, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRespuestasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcantAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        pRespuestasLayout.setVerticalGroup(
            pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRespuestasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(lblPrimerP, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pRespuestasLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel8))
                        .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRespuestasLayout.createSequentialGroup()
                        .addGroup(pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRespuestasLayout.createSequentialGroup()
                        .addGroup(pRespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcantAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(14, 14, 14))))
        );

        getContentPane().add(pRespuestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 690, 120));

        lblFondo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(204, 204, 204));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/degradados-wallpapers-3.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        control.salir();/// se llama al metodo salir del controlador
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (val_Empty()) {/// si val_empty es == true ejecuta el codigo
            ///instanciamos el objeto alumno q lo declaramos al inicio de la clase para poder utilizarlo en cualquier momento
            Alumno alm = new Alumno();
            //llenamos el objeto con los datos a traves de los metodos set de la clase alumno
            alm.setMatricula(txtMatricula.getText());
            alm.setNombre(txtNombre.getText());
            alm.setApellidoP(txtApellidoP.getText());
            alm.setApellidoM(txtApellidoM.getText());
            alm.setPromedio(cboPromedio.getSelectedIndex());
            control.guardar(alm);/// llamamos al metodo guardar del controlador
            control.limpiar(pDatos, 1);/// llamamos al metodo limpiar del controlador, mandamos como parametro el nombre del panel y 1 para txt y 2 para lbl
            cboPromedio.setSelectedIndex(0);
            txtMatricula.requestFocus();
            lblcantAlumnos.setText(String.valueOf(control.mostrar().size()));///nos muestra la cantidad de alumnos q tenemos registrados
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        control.nuevo();////// llamamos al metodo nuevo del controlador
        control.limpiar(pDatos, 1);////llamamos al metodo limpiar del controlador, mandamos como parametro el nombre del panel y 1 para txt y 2 para lbl
        control.limpiar(pRespuestas, 2);
        cboPromedio.setSelectedIndex(0);
        if (tblDatos.getRowCount() > 0) {
            tblDatos.setModel(tabla());
        }

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        control.salir();// se llama el metodo salir del controlador
    }//GEN-LAST:event_formWindowClosing

    private void BtnMostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostarActionPerformed
        int reg = control.mostrar().size();
        if (reg == 0) {
            JOptionPane.showMessageDialog(null, "No hay alumnos registrados");
        } else {
            DefaultTableModel m = tabla();
            Object[] columna = new Object[5];
            int media = 0, acumuladorProm = 0;
            int max = 0, indice = 0;
            for (int i = 0; i < control.mostrar().size(); i++) {

                columna[0] = control.mostrar().get(i).getMatricula();
                columna[1] = control.mostrar().get(i).getNombre();
                columna[2] = control.mostrar().get(i).getApellidoP();
                columna[3] = control.mostrar().get(i).getApellidoM();
                int promedio = control.mostrar().get(i).getPromedio();
                columna[4] = promedio;
                m.addRow(columna);
                acumuladorProm += promedio;// sumamos todos los promedio
                if (max < promedio) {//evaluamos para saber cual es el promedio mayor
                    max = promedio;
                    indice = i;///guardamos el valor del indice del promedio mayor para obtener los datos
                }
            }

            media = Math.round(acumuladorProm / reg);///calculamos la media
            String primerP = control.mostrar().get(indice).getNombre() + " " + control.mostrar().get(indice).getApellidoP() + " " + control.mostrar().get(indice).getApellidoP();
            tblDatos.setModel(m);//// se le entrega el modelo con todas las columnas a la tabla
            lblPrimerP.setText(primerP);
            lblPromedio.setText(String.valueOf(max));
            lblMedia.setText(String.valueOf(media));
        }
    }//GEN-LAST:event_BtnMostarActionPerformed

    private boolean val_Empty() {
        boolean v = false;
        if (txtMatricula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un número de matricula");
            txtMatricula.requestFocus();
        } else if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre");
            txtNombre.requestFocus();
        } else if (txtApellidoP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el apellido paterno");
            txtApellidoP.requestFocus();
        } else if (txtApellidoM.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el apellido materno");
            txtApellidoM.requestFocus();
        } else if (cboPromedio.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una nota de la lista");
            cboPromedio.requestFocus();
        } else {
            v = true;
        }
        return v;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Promedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMostar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboPromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblPrimerP;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblcantAlumnos;
    public javax.swing.JPanel pDatos;
    private javax.swing.JPanel pRespuestas;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
